INSERT INTO
    products (
        seller_id,
        name,
        kategori,
        description,
        status,
        price,
        stock,
        image,
        created_at,
        updated_at
    )
VALUES
    (
        3,
        'Meja Belajar Minimalis',
        'meja',
        'Meja belajar kayu jati minimalis cocok untuk kamar sempit.',
        'aktif',
        450000.00,
        10,
        "https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=",
        NOW (),
        NOW ()
    ),
    (
        3,
        'Kursi Makan Rotan',
        'kursi',
        'Kursi makan dengan anyaman rotan dan kaki besi anti karat.',
        'aktif',
        275000.00,
        15,
        "https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=",
        NOW (),
        NOW ()
    ),
    (
        3,
        'Lemari 2 Pintu Sliding',
        'lemari',
        'Lemari sliding 2 pintu dengan kaca full body dan rak dalam.',
        'non-aktif',
        1250000.00,
        5,
        "https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=",
        NOW (),
        NOW ()
    ),
    (
        3,
        'Kasur Busa Super',
        'kasur',
        'Kasur busa anti kempes ukuran 160x200 dengan sarung bonus.',
        'aktif',
        980000.00,
        8,
        "https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=",
        NOW (),
        NOW ()
    ),
    (
        3,
        'Rak Buku Sudut',
        'rak',
        'Rak buku minimalis untuk sudut ruangan, muat hingga 50 buku.',
        'aktif',
        320000.00,
        20,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Kursi Kayu Vintage',
        'kursi',
        'Kursi kayu bergaya vintage cocok untuk ruang tamu klasik.',
        'aktif',
        350000.00,
        12,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Meja Tamu Kayu Solid',
        'meja',
        'Meja tamu berbahan kayu solid dengan finishing natural.',
        'aktif',
        650000.00,
        7,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Sofa 2 Dudukan Elegan',
        'sofa',
        'Sofa dua dudukan dengan bantalan empuk dan kain beludru.',
        'non-aktif',
        1850000.00,
        3,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Rak Dinding Minimalis',
        'rak',
        'Rak dinding 3 susun dari kayu jati cocok untuk dekorasi rumah.',
        'aktif',
        220000.00,
        18,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Dekorasi Dinding Daun Emas',
        'dekorasi',
        'Hiasan dinding motif daun dengan finishing emas mengkilap.',
        'aktif',
        155000.00,
        25,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Meja Kerja Modern',
        'meja',
        'Meja kerja dengan desain modern dan laci penyimpanan serbaguna.',
        'aktif',
        775000.00,
        9,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Kursi Lipat Serbaguna',
        'kursi',
        'Kursi lipat ringan dan kuat, cocok untuk acara indoor dan outdoor.',
        'aktif',
        190000.00,
        30,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Lemari Pakaian Kayu Jati',
        'lemari',
        'Lemari pakaian 3 pintu dengan gantungan dan laci penyimpanan dalam.',
        'non-aktif',
        1980000.00,
        4,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Kasur Springbed Queen Size',
        'kasur',
        'Kasur springbed ukuran queen dengan tingkat kenyamanan tinggi.',
        'aktif',
        2100000.00,
        6,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Dekorasi Vas Bunga Keramik',
        'dekorasi',
        'Vas bunga keramik handmade dengan motif etnik cocok untuk ruang tamu.',
        'aktif',
        98000.00,
        40,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Sofa L Minimalis Abu',
        'sofa',
        'Sofa bentuk L dengan warna abu-abu modern, cocok untuk ruang keluarga.',
        'aktif',
        2750000.00,
        2,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Rak Sepatu 3 Susun',
        'rak',
        'Rak sepatu dari kayu pinus dengan kapasitas hingga 9 pasang sepatu.',
        'aktif',
        185000.00,
        14,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Meja Rias Cermin LED',
        'meja',
        'Meja rias dengan cermin LED dan laci penyimpanan makeup.',
        'non-aktif',
        890000.00,
        5,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Dekorasi Dinding Kaligrafi',
        'dekorasi',
        'Hiasan dinding kaligrafi islami dari kayu jati ukir.',
        'aktif',
        245000.00,
        22,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    ),
    (
        3,
        'Kasur Lantai Lipat',
        'kasur',
        'Kasur lipat 3 susun yang nyaman untuk tamu atau kamar anak.',
        'aktif',
        325000.00,
        11,
        'https://media.istockphoto.com/id/1168952666/id/foto/kursi-kayu-vintage-retro-terisolasi-di-atas-putih-termasuk-jalur-kliping.jpg?s=1024x1024&w=is&k=20&c=-8SYRjMjCjdSnNOOWr3bG8w3JgsQWQqUQSQqiUARtoE=',
        NOW (),
        NOW ()
    );